### ISSUE TITLE
Open a discussion page & is entso-E useable for german tibber customers (nordpool shows for germany prices 3 - 7 cent too high since api change on monday)

### ISSUE THREAD

**Issue by typxxi** [kotope/aio_energy_management#23]
I suggest to open a discussion page for newbies like me a bit lost between the blog and github here

also cause due to the breaking of nordpool at least for me and german customers who had used before the region "DE-LU" which is no longer supported and has been replaced by "GER" which sounds easy, but there has been a deeper change behind the scenes.

Right now I am using tibber , I have tibber app and till monday the prices of tibber and the nordpool integration using the "DE-LU" region had worked perfectly  - on 1 occasion a difference of 0,01 cent.

Since the new api arrived or changed yesterday I have differences of up to 7 cent, nordpool says 47 cents monday morning and tibber says 39,8 cents or so. And my "calculation line for fees and vat" has not changed cause there was no change, but the api change to GER leads to big deviations I do not really wanna to deal with, or I have to make sure that those deviations are constant and not changing, but I guess that will also go wrong considering that the cheapest hour(s) is also based on deviation from median. 

npool figures for today and tomorrow, below the same based on tibber integration
tomorrow 6 pm 47,5 cent based on nordpool and 41,3 cent based on tibber which are 6,2 cents .. even though I know that this is all about relations but the gap is changing big time cause today it was 33,1 versus 29,8 (most expensive hours), so just 3,3 cent . The price dropped by 15 cent or 1/3 but the gap is 50% less from 6,2 to 3,3 cents but at least the hours was the same: 7 pm
![image](https://github.com/user-attachments/assets/077afd8c-1442-46f6-a52b-6effd5522826)

Just to give you an idea what we are dealing with in reality, but still will have to pay the tibber prices.
![image](https://github.com/user-attachments/assets/c20c3d26-5ad5-4107-9168-51abd0d4e6fd)

All this happened when I was about to start our AIO management based on nordpool due to reaching the limits of our battery in the past week. 

Now the only way out looks like getting the Entso-E integration running and checked for deviations.  

So my main issue or rather question is if entso-E integration would also work for germany and if I can do the same you had explained in your blogs over the past 2 years when you had started. I was reading along cause it took a lot longer to build the 25 kWp system diy and its 2 batteries of 22 kWh in total plus a charger and repairing the roof first which no one had expected . 

I will try to install entso-E and hope for the best.

### My current starting point is a simple one: 

the battery is running of out of juice in the morning during peak time and therefore I have 2 alternatives.
1 charging during cheap night hours like 20 cent
or
2 stop discharging during cheap night hours and using AC from the grid instead for 20 cent

**big difference ?** 
no losses of 15% to 20% for the roudtrip which means saving 3 to 4 cents more by using direct AC and a good battery recovery meanwhile
![image](https://github.com/user-attachments/assets/c245221b-aecc-4872-b900-f8d49dc9e80d)

**Comment by kotope** [comment]
Good advice, I opened a discussion forum.

Would you mind moving this under new discussion forum so I can close this issue in few days :-)

I will also try to read your question more throughly once I finish my daily work today and see if I can help you more.

**Comment by typxxi** [comment]
I have no clue how to do that cause from other sites like evcc  I know that the owners / administrators can do that. 
But I will close this topic cause it is more or less outdated due to my progress of today and the questions have moved ahead.

So I will close it now and might copy parts of that into a new issue or request if there is a possibility to use the genuine tibber integration sensors as alternative source cause neither nordpool nor entso are matching our german tibber prices .

I have used the modifyer template for nordpool for months when it worked perfectly which meant 0,01 cent deviation in 1 out 6 cases, but since monday and their new idea of api implementation and changing from DE-LU to GER the diffences have exploded even with the same modifier template.

Entso-E is also overpricing and it is hard to judge cause that overpricing is depening on the price I guess. 
It is not a constant offset like always 1,5 cent too high.  But that is the story for a new request how to get benefit from aio the easiest way using the tibber sensor.
