### ISSUE TITLE
Every other day values not calclulated if starting_today is false and last_hour is 23 

### ISSUE THREAD

**Issue by kotope** [kotope/aio_energy_management#3]
As the day changes to next day at 00:00, every other day will run on failsafe on conditions where starting_today is false and last_hour is 23.

Until fix is available, use last_hour as 22 to skip the final hour.

This is going to be fixed at the same when creating support to show two possible values if expiration is after nordpool publishing hours.

**Comment by xoferz** [comment]
came here to say just that :-)

**Comment by kotope** [comment]
Unfortunately fixing this has been taking some time, mostly due my busy schedules during last weeks.

Good news though that the changes are almost written now and just needs some final touches and testing :-)

**Comment by xoferz** [comment]
Today is missing for me again. Last_hour is 22. Nordpool info itself for today is ok.

**Comment by kotope** [comment]
Most probably something has happened between 23.00-00.00 that the Nord Pool data has not been received by aio energy management. If you have logs available between 23-00 and dare to send me those, I can verify the cause of your issue.

Anyhow, during the weekend I pushed required changed to 'feature/next_item' and now I'm running the new version on my own environment for few days before making the release. Just to be sure I won't break anything :-)
So far everything has been fine and I will be making a new release tomorrow if no surprises comes.

**Comment by xoferz** [comment]
There is nothing in the log about this unfortunately, I checked. 
Current conf:
`aio_energy_management:
  calendar:
      name: energy_management
      unique_id: energy_management
  cheapest_hours:
    - nordpool_entity: sensor.nordpool
      unique_id: nordpool_cheapest_2h_nonconsecutive
      name: "Cheapest 2h non-consecutive"
      first_hour: 0
      last_hour: 22
      starting_today: false
      number_of_hours: 2
      sequential: False
      failsafe_starting_hour: 22    
    - nordpool_entity: sensor.nordpool
      unique_id: nordpool_cheapest_4h_consecutive
      name: "Cheapest 4h consecutive"
      first_hour: 0
      last_hour: 22
      starting_today: false
      number_of_hours: 4
      sequential: True
      failsafe_starting_hour: 22`

Both calendars are empty.
Nordpool data has been there - I also use nordpool_diff component and that keeps on working.

**Comment by xoferz** [comment]
And they appeared for tomorrow, 17/09
Seems still every other day

**Comment by kotope** [comment]
This should now be fixed with the v0.1.1 release.

Please re-open if issue still persists :)
